# Generated by Django 2.1.5 on 2020-03-09 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name')),
                ('cnt_email', models.PositiveIntegerField(default=25, verbose_name='Email')),
                ('cnt_message', models.PositiveIntegerField(default=5, verbose_name='Message')),
                ('cnt_status', models.PositiveIntegerField(choices=[(0, 'Active'), (2, 'Pending'), (3, 'Done')], verbose_name='Status')),
                ('cnt_created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('cnt_modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modification Date')),
                ('cnt_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contact',
            },
        ),
    ]
