# Generated by Django 2.0.7 on 2020-03-08 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnf_lap_time', models.PositiveIntegerField(verbose_name='Pomodoros Time')),
                ('cnf_time_short_brake', models.PositiveIntegerField(verbose_name='Time Short Brake')),
                ('cnf_time_long_brake', models.PositiveIntegerField(verbose_name='Time Long Brake')),
                ('cnf_created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('cnf_modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modification Date')),
                ('cnf_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Configs',
            },
        ),
    ]
