# Generated by Django 2.1.5 on 2020-03-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_config_cnf_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='cnf_lap_time',
            field=models.PositiveIntegerField(default=25, verbose_name='Pomodoros Time'),
        ),
        migrations.AlterField(
            model_name='config',
            name='cnf_time_long_brake',
            field=models.PositiveIntegerField(default=10, verbose_name='Time Long Brake'),
        ),
        migrations.AlterField(
            model_name='config',
            name='cnf_time_short_brake',
            field=models.PositiveIntegerField(default=5, verbose_name='Time Short Brake'),
        ),
    ]
