# Generated by Django 2.0.7 on 2020-03-08 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsk_title', models.CharField(max_length=150, verbose_name='Nickname')),
                ('tsk_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('tsk_status', models.CharField(choices=[(0, 'Pending'), (1, 'Done')], max_length=15, verbose_name='Status')),
                ('tsk_assignted_time', models.PositiveIntegerField(verbose_name='Assignated Time')),
                ('tsk_created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('tsk_modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modification Date')),
                ('tsk_config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configs.Config', verbose_name='Configuration')),
                ('tsk_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
