# Generated by Django 2.1.5 on 2020-03-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tsk_status',
            field=models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Done')], max_length=15, verbose_name='Status'),
        ),
    ]
