# Generated by Django 2.1.5 on 2020-03-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200308_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tsk_status',
            field=models.PositiveIntegerField(choices=[(0, 'Pending'), (1, 'Done')], verbose_name='Status'),
        ),
    ]
