# Generated by Django 2.1.5 on 2020-03-08 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200308_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tsk_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.Config', verbose_name='Configuration'),
        ),
    ]
